name: asulado

services:
  postgres:
    image: postgres:16
    container_name: asulado-db
    restart: always
    environment:
      POSTGRES_DB: asulado
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - asulado-net

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5052:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - asulado-net

  sonarqube:
    image: sonarqube:lts-community
    container_name: sonarqube
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    networks:
      - asulado-net

#  asulado-app:
#    build:
#      context: ..
#      dockerfile: deployment/Dockerfile
#    container_name: asulado-app
#    restart: always
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_PROFILES_ACTIVE: dev
#      SPRING_R2DBC_URL: r2dbc:postgresql://postgres:5432/asulado
#      SPRING_R2DBC_USERNAME: postgres
#      SPRING_R2DBC_PASSWORD: postgres
#      SPRING_LIQUIBASE_ENABLED: true
#      SPRING_LIQUIBASE_CHANGE_LOG: classpath:db/changelog/db.changelog-master.yaml
#    depends_on:
#      - postgres
#      - sonarqube
#    networks:
#      - asulado-net

volumes:
  postgres_data:
  pgadmin_data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:

networks:
  asulado-net:
    driver: bridge
